
encoder:
  # ---  dim of trunk feature vector ---
  trunk_embed_dim:
    vision: 1280
    text:    768
    audio:   768
    depth:   384
    thermal: 768
    imu:     512
    tactile: 768
    eeg:     768

  # ---  dim of alined/common feature vector ---
  output_embed_dim:
    common:  1024      # Fixed  
    vision:  0  
    text:    0
    audio:   0
    depth:   0
    thermal: 0
    imu:     0
    tactile: 0
    eeg:     0
    

  # head
  add_new_output_head: False  # output_embed_dim中任意specific dim，则需add_new_output_head
  use_both_head: False

  # postprocessor
  use_postprocessors_outencoder: False
  learnable_postprocessors: False

decoder:
  use_decoder: True
  with_cls_token: True  # the decoder takes both 'cls_token' and 'patch_tokens' as inputs.
  input_projection: True # align the encoder trunk output dim with decoder input dim and add encoder trunk output into reconstruction 

  # input_embed_dim:  # 可以根据 encoder.output_embed_dim 推算出来
  #   vision:  1280  # 1024 + 256  # encoder.output_embed_dim.common + encoder.output_embed_dim.vision
  #   image:   1280  # 1024 + 256
  #   video:   1280  # 1024 + 256
  #   audio:   1280  # 1024+ 256
  #   depth:   1280  # 1024+ 256
  #   thermal: 1280  # 1024+ 256
  #   imu:     1280  # 1024+ 256
  
  # decoder_trunk
  trunk_embed_dim:
    vision:  512
    audio:   512
    depth:   512
    thermal: 512
    imu:     512
    tactile: 512
    eeg:     512

  # num of stacked attention blocks in the transformer trunk
  decoder_depth: 8        # , default 8
  
  # decoder_head
  hidden_channels:
    vision:  128
    audio:   128
    depth:   128
    thermal: 128
    imu:     128
    tactile: 128
    eeg:     128

# vector_quantise is None 