encoder:
  trunk_embed_dim:
    vision: 1280
    text: 768
    audio: 768
    depth: 384
    thermal: 768
    imu: 512
    tactile: 768
    eeg: 768
  output_embed_dim:
    common: 1024
    vision: 1024
    text: 0
    audio: 1024
    depth: 1024
    thermal: 1024
    imu: 1024
    tactile: 1024
    eeg: 1024
  add_new_output_head: true
  use_both_head: true
  use_postprocessors_outencoder: true
  learnable_postprocessors: true

decoder:
  use_decoder: True
  with_cls_token: True  # the decoder takes both 'cls_token' and 'patch_tokens' as inputs.
  input_projection: True # align the encoder trunk output dim with decoder input dim and add encoder trunk output into reconstruction 
  
  input_embed_dim:
    image: 2048
    video: 2048
    vision: 2048
    audio: 2048
    depth: 2048
    thermal: 2048
    imu: 2048
  
  encoder_trunk_embed_dim:
    vision: 1280
    text: 768
    audio: 768
    depth: 384
    thermal: 768
    imu: 512
    tactile: 768
    eeg: 768
    
  # decoder_trunk
  trunk_embed_dim:
    vision:  512
    audio:   512
    depth:   512
    thermal: 512
    imu:     512
    tactile: 512
    eeg:     512

  # num of stacked attention blocks in the transformer trunk
  decoder_depth: 8        # , default 8
  
  # decoder_head
  hidden_channels:
    vision:  128
    audio:   128
    depth:   128
    thermal: 128
    imu:     128
    tactile: 128
    eeg:     128

vector_quantise:
  use_mvq: true
  single_vq_embed_num: 256
  single_vq_embed_dim: 1024
  vq_all_token: true
  distance: cos
  anchor: random
  ema_update: true
  shuffle_scale: 0
  sim_loss: false
  contras_loss: true
  uni_loss: true
  share_codebook: false
  norm_code: true
  kmeans_init: true
  seg_type: 1
  codevector_num:
    common: 1024
    text: 256
    vision: 256
    depth: 256
    audio: 256
    thermal: 256
    imu: 256
    tactile: 256
    eeg: 256
  codevector_dim:
    common: 8
    text: 0
    vision: 8
    depth: 8
    audio: 8
    thermal: 8
    imu: 8
    tactile: 8
    eeg: 8
  input_vector_dim:
    common: 1024
    vision: 1024
    text: 0
    audio: 1024
    depth: 1024
    thermal: 1024
    imu: 1024
    tactile: 256
    eeg: 1024
