# # # # #
# Config file for training the model on SUN-RGBD dataset.
#
# # # # #

expname: nyu_exp

# log
# loggers: wandb  # 通过sh 设置， 不设置则不使用log

# data
datasets: nyu
scale_factor: 20                  # replicate the dataset x scale_factor
batch_size: 10                     # on each GPU
max_epochs: 40
num_workers: 8                   # Number of workers for data loading
text_template: imagenet           # simple, imagenet or scene

# train
train: True
train_mode: lora  # lora, fulltune, headtune
modality_train: [depth, vision, text]
modality_pair: [depth, vision, text]    # modality to aline
modality_eval: depth              # Modality to eval, choices=["vision", "text", "audio", "thermal", "depth", "imu"]
modality_reconstruction: [vision, depth]  # 必须在modality_pair中，否则会被过滤掉

# params
lr: 5e-4
lr_new: 5e-4
weight_decay: 1e-4
momentum_betas: [0.9, 0.95]
gradient_clip_val: 1.0
temperature: 0.07                 # Temperature parameter for InfoNCE loss
self_contrast: False
intra_anchor_align: True # enable text and vision alignment when three modalities are aligned

# loss
val_loss: False  # whether to calculate validation loss
loss_vq_weight: 1000.0
loss_vq_reg_weight: 0.01
loss_cmcm_weight: 0.1
loss_modal_decomp_weight: 0.1
loss_uniform_weight: 1.0

# -------------------- Common settings -------------------
seed: 43                          # Random seed for reproducibility

# lora
lora_rank: 4                      # Rank of LoRA layers
lora_modality_names: [depth]          # Modality names to apply LoRA
lora_layer_idxs_depth: [6, 7, 8, 9, 10, 11]
lora_module_mode: all  # all, attn_out, attn

# Directory containing the datasets
# create symbolic link: ln -s [src] ./.datasets/RGBD-SUN
sun_root: ./.datasets/depth/RGBD-SUN
nyu_root: ./.datasets/depth/RGBD-SUN

