# # # # #
# Config file for training the model on AudioSet dataset.
#
# # # # #

# log
# loggers: wandb

# data
datasets: audiocaps
scale_factor: 1                 # replicate the dataset x scale_factor
batch_size: 10                  # on each GPU
max_epochs: 40
num_workers: 8                   # Number of workers for data loading

# train
train: True
train_mode: lora
modality_train: [audio, vision, text]
modality_pair: [audio, vision, text]    # modality to aline
modality_eval: audio              # Modality to eval, choices=["vision", "text", "audio", "thermal", "depth", "imu"]
modality_reconstruction: [vision, audio]

# params
lr: 5e-5
lr_new: 5e-4
weight_decay: 1e-4
momentum_betas: [0.9, 0.95]
gradient_clip_val: 1.0
temperature: 0.05                 # Temperature parameter for InfoNCE loss
self_contrast: False
intra_anchor_align: True # enable text and vision alignment when three modalities are aligned

# loss
val_loss: True  # whether to calculate validation loss
loss_vq_weight: 50
loss_vq_reg_weight: 0.01
loss_cmcm_weight: 1.0
loss_modal_decomp_weight: 0.1
loss_uniform_weight: 1.0

# -------------------- Common settings -------------------
seed: 43                          # Random seed for reproducibility

# lora
lora_rank: 4                      # Rank of LoRA layers
lora_modality_names: [audio]          # Modality names to apply LoRA
lora_layer_idxs_audio: [6, 7, 8, 9, 10, 11]
lora_module_mode: all  # all, attn_out, attn

# Directory containing the datasets
# create symbolic link: ln -s [src] ./.datasets/RGBD-SUN
audiocaps_root: ./.datasets/AudioCaps
